defaults:
  - default
  - net/embedding: PatchedConv_Embedding
  - net/encoder: encoder
  - net/decoder: decoder
  - net/mapper: DLinear

net:
  _target_: src.models.components.biRec.Model
  d_model: 16
  encoder:
    num_channels: ${data.num_channels}
    embedding_type: ${model.net.embedding.type}
    patch_len: ${model.net.embedding.patch_len}
    with_ch: true
    with_tem: true
  decoder:
    num_channels: ${data.num_channels}
    embedding_type: ${model.net.embedding.type}
    patch_len: ${model.net.embedding.patch_len}



