defaults:
  - default
net:
  _target_: src.models.components.DLinear.Model
  input_len: ${data.input_len}
  output_len: ${data.output_len}
  num_channels: ${data.num_channels}
  moving_avg: 25
  individual: false
  with_revin: true
  eps: 1e-8

model_name: DLinear
scale: ${data.scale}
# compile model for faster training with pytorch 2.0
compile: false
