defaults:
  - default

net:
  _target_: src.models.components.RLinear.Model
  input_len: ${data.input_len}
  output_len: ${data.output_len}
  num_channels: ${data.num_channels}
  individual: false
  eps: 1e-8