defaults:
  - default
aux_model:
  _target_: src.models.components.RLinear.Model
  _partial_: true
  input_len: ${data.input_len}
  output_len: ${data.output_len}
  num_channels: ${data.num_channels}
  individual: false
  eps: 1e-5

aux_model_stu:
  _target_: src.models.components.PatchTST.Model
  _partial_: true
  d_model: 128
  d_ff: 128
  input_len: ${data.input_len}
  output_len: ${data.output_len}
  num_heads: 4
  num_layers: 2
  num_channels: ${data.num_channels}
  patch_len: 16
  stride: 8
