defaults:
  - default
aux_model:
  _target_: src.models.components.Linear.Model
  _partial_: true
  input_len: ${data.input_len}
  output_len: ${data.output_len}
  num_channels: ${data.num_channels}
  individual: false
  eps: 1e-8

aux_model_stu: null