# @package _global_

defaults:
  - _self_
  - data: ETTh1 # choose datamodule with `test_dataloader()` for evaluation
  - model: biRecMulti
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - task: forecasting

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: null


